# Site Settings Definitions for MPC RSS
categories:
  mpcRss:
    label: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:mpcRss.label'
    description: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:mpcRss.description'
  mpcRssView:
    label: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:mpcRssView.label'
    description: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:mpcRssView.description'

settings:
  plugin.tx_mpcrss.view.templateRootPath:
    label: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:plugin.tx_mpcrss.view.templateRootPath.label'
    description: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:plugin.tx_mpcrss.view.templateRootPath.description'
    type: string
    default: 'EXT:mpc_rss/Resources/Private/Templates/'
    category: mpcRssView

  plugin.tx_mpcrss.view.partialRootPath:
    label: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:plugin.tx_mpcrss.view.partialRootPath.label'
    description: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:plugin.tx_mpcrss.view.partialRootPath.description'
    type: string
    default: 'EXT:mpc_rss/Resources/Private/Partials/'
    category: mpcRssView

  plugin.tx_mpcrss.view.layoutRootPath:
    label: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:plugin.tx_mpcrss.view.layoutRootPath.label'
    description: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:plugin.tx_mpcrss.view.layoutRootPath.description'
    type: string
    default: 'EXT:mpc_rss/Resources/Private/Layouts/'
    category: mpcRssView
  plugin.tx_mpcrss.settings.maxItems:
    label: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:plugin.tx_mpcrss.settings.maxItems.label'
    description: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:plugin.tx_mpcrss.settings.maxItems.description'
    type: int
    default: 9
    category: mpcRss

  plugin.tx_mpcrss.settings.cacheLifetime:
    label: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:plugin.tx_mpcrss.settings.cacheLifetime.label'
    description: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:plugin.tx_mpcrss.settings.cacheLifetime.description'
    type: int
    default: 1800
    category: mpcRss

  plugin.tx_mpcrss.settings.includeCategories:
    label: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:plugin.tx_mpcrss.settings.includeCategories.label'
    description: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:plugin.tx_mpcrss.settings.includeCategories.description'
    type: string
    default: ''
    category: mpcRss

  plugin.tx_mpcrss.settings.excludeCategories:
    label: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:plugin.tx_mpcrss.settings.excludeCategories.label'
    description: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:plugin.tx_mpcrss.settings.excludeCategories.description'
    type: string
    default: ''
    category: mpcRss

  plugin.tx_mpcrss.settings.showCategoryFilter:
    label: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:plugin.tx_mpcrss.settings.showCategoryFilter.label'
    description: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:plugin.tx_mpcrss.settings.showCategoryFilter.description'
    type: bool
    default: true
    category: mpcRss

  plugin.tx_mpcrss.settings.paginate:
    label: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:plugin.tx_mpcrss.settings.paginate.label'
    description: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:plugin.tx_mpcrss.settings.paginate.description'
    type: bool
    default: false
    category: mpcRss

  plugin.tx_mpcrss.settings.itemsPerPage:
    label: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:plugin.tx_mpcrss.settings.itemsPerPage.label'
    description: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:plugin.tx_mpcrss.settings.itemsPerPage.description'
    type: int
    default: 10
    category: mpcRss

  plugin.tx_mpcrss.settings.defaultCategory:
    label: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:plugin.tx_mpcrss.settings.defaultCategory.label'
    description: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:plugin.tx_mpcrss.settings.defaultCategory.description'
    type: string
    default: 'Politik'
    category: mpcRss

  plugin.tx_mpcrss.settings.groupingMode:
    label: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:plugin.tx_mpcrss.settings.groupingMode.label'
    description: 'LLL:EXT:mpc_rss/Resources/Private/Language/locallang_sitesettings.xlf:plugin.tx_mpcrss.settings.groupingMode.description'
    type: string
    default: 'category'
    category: mpcRss

